name: 12 JSON functions
on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env: 
          CONTEXT: ${{ toJSON(github) }}      # github コンテキストを JSON 文字列でダンプ